name: 'snapchat_ads_source_integration_tests'

version: '0.4.0'
profile: 'integration_tests'
config-version: 2

vars: 
  snapchat_ads_source:
    snapchat_ads__ad_account_history_identifier:  "snapchat_ad_account_history_data"
    snapchat_ads__ad_history_identifier: "snapchat_ad_history_data"
    snapchat_ads__ad_hourly_report_identifier: "snapchat_ad_hourly_report_data"
    snapchat_ads__ad_squad_history_identifier: "snapchat_ad_squad_history_data"
    snapchat_ads__campaign_history_identifier: "snapchat_campaign_history_data"
    snapchat_ads__creative_history_identifier: "snapchat_creative_history_data"
    snapchat_ads__creative_url_tag_history_identifier: "snapchat_creative_url_tag_history_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']